Check for template existence...

diff --git a/templates/Jenkinsfile_dist b/templates/Jenkinsfile_dist
--- a/templates/Jenkinsfile_dist
+++ b/templates/Jenkinsfile_dist
@@ -215,6 +215,7 @@ spec:
       args:
         - cd /opt/midpoint ;
           ./download-midpoint ${DOCKERTAG} midpoint.tar.gz ;
+          overallFound=0 ;
           /usr/local/bin/prepare_layer midpoint.tar.gz ${DOCKERTAG} ;
           echo -n \"/usr/local/bin/crane index append\" >combine_command ;
           crane ls registry.lab.evolveum.com/midpoint > image_list ;
@@ -225,17 +226,20 @@ spec:
           for s in \\\$(uniq combine_platform_sorted) ;
           do
           toProcess=\"${IMAGEOS}\" ;
-          echo \"Looking for the remplate on platform \\\${s} - \\\${toProcess} \\\${toProcess%.*} \${osID}\" ;
+          found=0 ;
+          echo \"Looking for the template on platform \\\${s} - \\\${toProcess} \\\${toProcess%.*} \${osID}\" ;
           for i in \\\${toProcess} \\\${toProcess%.*} \${osID} ;
           do
           if [ \\\$(grep \"^template-\\\${s}-${JAVAVER}-\\\${i}\\\$\" image_list | wc -l) -eq 1 ] ;
           then
-          echo \"Found match - Base OS \\\${i} & Java version ${JAVAVER} @ \\\${s}\" ;
+          echo \"Found match : Base OS \\\${i} & Java version ${JAVAVER} @ \\\${s}\" ;
           echo -n \" -m registry-\${timestamp}.lab.evolveum.com/midpoint:build-${DOCKERTAG}-\\\${s}-${JAVAVER}-\\\${i}\" >>combine_command ;
           /usr/local/bin/crane append -b registry.lab.evolveum.com/midpoint:template-\\\${s}-${JAVAVER}-\\\${i} -f midpoint-opt-${DOCKERTAG}.tar -t registry-\${timestamp}.lab.evolveum.com/midpoint:build-${DOCKERTAG}-\\\${s}-${JAVAVER}-\\\${i} ;
+	  found=1 ; overallFound=1;
           break;
           fi ;
           done ;
+          if [ \${found} -eq 0 ] ; then echo "NOT Found : \\\${i} w Java ${JAVAVER} @ \\\${s} " ; fi ;
           echo \".\";
           done ;
           echo ;
@@ -249,6 +253,7 @@ spec:
           /usr/local/bin/crane ls registry-\${timestamp}.lab.evolveum.com/midpoint ;
           echo ;
           /usr/local/bin/crane manifest registry-\${timestamp}.lab.evolveum.com/midpoint:build-${DOCKERTAG}-${IMAGEOS}-\${timestamp} ;
+          if [ \${overallFound} -eq 0 ] ; then exit 123 ; fi ;
       imagePullPolicy: Always 
   restartPolicy: Never
 EOF
